### PR TITLE
Responsive design

### PR DESCRIPTION
**Pull request by Madis0**
Just a viewport meta tag.

### CODE REVIEW

**Comment by csagan5** [comment]
@Madis0 I have updated the CSS from the Jekyll tactile theme that is being used. I believe that fixes the viewport problem.

**Comment by Madis0** [comment]
Not seeing any differences in the website yet...

**Comment by csagan5** [comment]
The change is already in place, you can read the CSS here:

https://github.com/bromite/bromite.github.io/blob/master/assets/css/style.css#L373

It does not improve the mobile visualization?

**Comment by Madis0** [comment]
I see. It looks decent on landscape but too small still on portrait.

screenshot_bromite_20181220-101242
screenshot_bromite_20181220-101159

**Comment by csagan5** [comment]
I suggest proposing improvements to theme upstream: https://github.com/pages-themes/tactile

It is an official Github pages theme.

**Comment by Calinou** [comment]
Would it be acceptable to switch themes to something more mobile-friendly? I regularly visit bromite.org to download the latest version, but I always have to zoom in which feels inconvenient.

If desired, I could come up with a custom design too :slightly_smiling_face:

**Comment by csagan5** [comment]
@Calinou it would be best to propose custom CSS changes to theme. I can use them for Bromite's website if they're not relevant for upstream.

I am saying this because I had to cleanup the tactile theme from a lot of third-party hosted content and any new theme would have to go through this process, thus the most effective solution is to fix the current font size issues/layout perhaps?

**Comment by csagan5** [comment]
> I see. It looks decent on landscape but too small still on portrait.

@Madis0 I incorporated the missing line `<meta name="viewport" content="width=device-width, initial-scale=1">` and now it looks better. This was present upstream in the tactile theme but not on the old version used here, so I was mistaken in thinking that the CSS update alone would suffice.

It now looks a bit better on mobile.

**Pull request closed without merging**
